repos:
  # Linting and formatting with ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.1.15'
    hooks:
      - id: ruff
        args: ['--fix', '--line-length=100']

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.408
    hooks:
    - id: pyright

  # YAML formatting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.5.0'
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: debug-statements
      - id: mixed-line-ending
      - id: check-added-large-files
        args: ['--maxkb=1000']

  # Security checks
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: 'v1.5.4'
    hooks:
      - id: forbid-crlf
      - id: forbid-tabs

ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
